# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofile.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprotofile.proto\x12\tprotofile\"2\n\x12\x43ombineSetsRequest\x12\x1c\n\x04sets\x18\x01 \x03(\x0b\x32\x0e.protofile.Set\";\n\x13\x43ombineSetsResponse\x12$\n\x0c\x63ombined_set\x18\x01 \x01(\x0b\x32\x0e.protofile.Set\"\x15\n\x03Set\x12\x0e\n\x06values\x18\x01 \x03(\x05\"(\n\nAddRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"0\n\x12\x43oncatenateRequest\x12\x0c\n\x04str1\x18\x01 \x01(\t\x12\x0c\n\x04str2\x18\x02 \x01(\t\"%\n\x13\x43oncatenateResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xe3\x01\n\tProtoFile\x12\x36\n\x03\x41\x64\x64\x12\x15.protofile.AddRequest\x1a\x16.protofile.AddResponse\"\x00\x12N\n\x0b\x43oncatenate\x12\x1d.protofile.ConcatenateRequest\x1a\x1e.protofile.ConcatenateResponse\"\x00\x12N\n\x0b\x43ombineSets\x12\x1d.protofile.CombineSetsRequest\x1a\x1e.protofile.CombineSetsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protofile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMBINESETSREQUEST']._serialized_start=30
  _globals['_COMBINESETSREQUEST']._serialized_end=80
  _globals['_COMBINESETSRESPONSE']._serialized_start=82
  _globals['_COMBINESETSRESPONSE']._serialized_end=141
  _globals['_SET']._serialized_start=143
  _globals['_SET']._serialized_end=164
  _globals['_ADDREQUEST']._serialized_start=166
  _globals['_ADDREQUEST']._serialized_end=206
  _globals['_ADDRESPONSE']._serialized_start=208
  _globals['_ADDRESPONSE']._serialized_end=237
  _globals['_CONCATENATEREQUEST']._serialized_start=239
  _globals['_CONCATENATEREQUEST']._serialized_end=287
  _globals['_CONCATENATERESPONSE']._serialized_start=289
  _globals['_CONCATENATERESPONSE']._serialized_end=326
  _globals['_PROTOFILE']._serialized_start=329
  _globals['_PROTOFILE']._serialized_end=556
# @@protoc_insertion_point(module_scope)
